### ISSUE TITLE
Pioneer device not recognized

### ISSUE THREAD

**Issue by acresp** [nitaybz/homebridge-onkyo-pioneer#1]
Hello,

Good to know that someone decided to write a new plugin, I hope as a true "AV Receiver" accessory ? 🙂 
I tried to install it and configure my Pioneer VSX-1123-K but it was not recognized.

It's working with other Pioneer plugins and via the Pioneer Remote App.

Wishing all good for your work, thanks !

Regards

**Comment by nitaybz** [comment]
Hey... it is a real avr accessory in HomeKit.
But I think your model might not be supported... did you try to turn on discover?
Did you add the up of the receiver to the config?
I don't have proper documentation yet but there will be pretty soon

**Comment by acresp** [comment]
Here is the "error" log i have in homebridge

> [12/16/2020, 7:29:53 PM] [OnkyoPioneer] Did not detect any device
> [12/16/2020, 7:29:53 PM] [OnkyoPioneer] retrying, retries left: 3..
> [12/16/2020, 7:29:53 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21xECNQSTN%0D
> [12/16/2020, 7:29:53 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21pECNQSTN%0D
> [12/16/2020, 7:29:53 PM] [OnkyoPioneer] Write ok
> [12/16/2020, 7:29:53 PM] [OnkyoPioneer] Write ok
> [12/16/2020, 7:29:54 PM] [OnkyoPioneer] Did not detect any device
> [12/16/2020, 7:29:54 PM] [OnkyoPioneer] retrying, retries left: 2..
> [12/16/2020, 7:29:54 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21xECNQSTN%0D
> [12/16/2020, 7:29:54 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21pECNQSTN%0D
> [12/16/2020, 7:29:54 PM] [OnkyoPioneer] Write ok
> [12/16/2020, 7:29:54 PM] [OnkyoPioneer] Write ok
> [12/16/2020, 7:29:55 PM] [OnkyoPioneer] Did not detect any device
> [12/16/2020, 7:29:55 PM] [OnkyoPioneer] retrying, retries left: 1..
> [12/16/2020, 7:29:55 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21xECNQSTN%0D
> [12/16/2020, 7:29:55 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21pECNQSTN%0D
> [12/16/2020, 7:29:55 PM] [OnkyoPioneer] Write ok
> [12/16/2020, 7:29:55 PM] [OnkyoPioneer] Write ok
> [12/16/2020, 7:29:56 PM] [OnkyoPioneer] Did not detect any device
> [12/16/2020, 7:29:56 PM] [OnkyoPioneer] retrying, retries left: 0..
> [12/16/2020, 7:29:56 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21xECNQSTN%0D
> [12/16/2020, 7:29:56 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21pECNQSTN%0D
> [12/16/2020, 7:29:56 PM] [OnkyoPioneer] Write ok
> [12/16/2020, 7:29:56 PM] [OnkyoPioneer] Write ok
> [12/16/2020, 7:29:57 PM] [OnkyoPioneer] Did not detect any device
> [12/16/2020, 7:29:57 PM] [OnkyoPioneer] Could not detect "Ampli Salon" receiver at 10.10.10.18!
> [12/16/2020, 7:29:57 PM] [OnkyoPioneer] Control may not work, check your receiver network connection
> [12/16/2020, 7:29:57 PM] [OnkyoPioneer] operation timed out
> [12/16/2020, 7:29:57 PM] [OnkyoPioneer] socket closed
> [12/16/2020, 7:29:57 PM] [OnkyoPioneer] Can't create new accessory for undetected device (10.10.10.18) !
> [12/16/2020, 7:29:57 PM] [OnkyoPioneer] skipping "Ampli Salon" device...

I tried the discover but it didn't work either.
For example, this plugin is working: [homebridge-pioneer-avr ](https://github.com/kazcangi/homebridge-pioneer-avr)
But it don't add it as a real avr accessory (and seems not supported anymore by it's dev)

**Comment by nitaybz** [comment]
Unfortunately if it's not discovering your device and if other pioneer plugins work for you, this plugin probably will not work for you. It uses special protocol, same as Onkyo receivers, and it's only being used by newer models of pioneer.

Sorry to let you down...

**Comment by acresp** [comment]
I understand, well if someday you want to take the code of a plugin that works and add the "old" protocol, I'm sure that would interest people :) But I imagine that it's probably lot of work...
