### ISSUE TITLE
To be recognize in HomeKit as a speaker?

### ISSUE THREAD

**Issue by barberboy18** [nitaybz/homebridge-onkyo-pioneer#3]
Hi is it possible to how HomeKit discover the receiver? Instead as a speaker ? I got issue when I ask Siri to play music , she tell me she can’t find speakers. Thank you

**Comment by nitaybz** [comment]
Speaker service in the home app is very limited... it will not allow you to play music, only official airrplay 2 devices are supported and allows you to play music or adjust volume.
