### ISSUE TITLE
Newb question... app working can turn on/off but how to change volume?

### ISSUE THREAD

**Issue by rcoda78** [nitaybz/homebridge-onkyo-pioneer#8]
I have this app working and able to turn on/off the receiver, and added to my HomeKit. But how do I change the volume? I don't see that in HomeKit. I see I can change the inputs, but not the volume. Thanks in advance for your assistance.

**Comment by nitaybz** [comment]
You have 2 ways to change the volume:
1. You can add a volume control from the plugin settings, you'll need to choose the type, I would recommend fan.
2. You can control the volume from the remote widget in the iPhone's control center, just pick the receiver from the TVs list and use the volume buttons of your iPhone.

Hope it helps

**Comment by rcoda78** [comment]
Thank you so much nitaybz for explaining that to me!
